# Generated by Django 5.1.1 on 2025-08-16 23:25

import django.db.models.deletion
import editor.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TempMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_request', models.CharField(choices=[('add', 'Add'), ('edit', 'Edit')], default='edit', max_length=4)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('rating', models.FloatField(default=7.0)),
                ('number_of_ratings', models.IntegerField(default=1)),
                ('start_year', models.DateField(blank=True, null=True)),
                ('end_year', models.DateField(blank=True, null=True)),
                ('number_of_seasons', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('number_of_series', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to=editor.models.cover_upload_path)),
                ('is_published', models.BooleanField(default=True, null=True)),
                ('genres', models.ManyToManyField(blank=True, to='main.genre')),
                ('media_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.media')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.status')),
                ('studios', models.ManyToManyField(blank=True, to='main.studio')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Request',
                'verbose_name_plural': 'Requests',
            },
        ),
    ]
